/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A3_EXAM.application;

/**
 * This class is the launching point for the GUI application by invoking methods from the GuiApplicationSetup class
 */
public class App {

    public static void main(String[] args) {
        GuiAppSetup guiApplicationSetup = new GuiAppSetup();
        guiApplicationSetup.performAppSetup(args);
    }


}